# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('category', models.CharField(choices=[(b'sushi', '\u0421\u0443\u0448\u0438'), (b'rolls', '\u0420\u043e\u043b\u043b\u044b'), (b'sets', '\u041d\u0430\u0431\u043e\u0440\u044b'), (b'tempura', '\u0422\u0435\u043c\u043f\u0443\u0440\u0430')], max_length=20)),
                ('image', models.ImageField(blank=True, height_field=200, upload_to=b'products/', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430', width_field=200)),
                ('price', models.FloatField(default=0.0, verbose_name='\u0426\u0435\u043d\u0430')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='\u0412 \u043f\u0440\u043e\u0434\u0430\u0436\u0435 \u043b\u0438 \u0442\u043e\u0432\u0430\u0440')),
                ('weight', models.IntegerField(default=0, verbose_name='\u0412\u0435\u0441 \u0432 \u0433\u0440\u0430\u043c\u0430\u0445')),
                ('calorie', models.IntegerField(default=0, verbose_name='\u041a\u0438\u043b\u043e\u043a\u0430\u043b\u043b\u043e\u0440\u0438\u0438')),
                ('tag', models.CharField(blank=True, choices=[(b'New', '\u041d\u043e\u0432\u0438\u043d\u043a\u0430'), (b'Spicy', '\u041e\u0441\u0442\u0440\u044b\u0439'), (b'Veg', '\u0412\u0435\u0433\u0435\u0442\u0435\u0440\u0438\u0430\u043d\u0441\u043a\u0438\u0439'), (b'Hit', '\u0425\u0438\u0442')], default=None, max_length=10, verbose_name='\u0411\u0438\u0440\u043a\u0430')),
                ('about', models.TextField(blank=True, verbose_name='\u041e \u0442\u043e\u0432\u0430\u0440\u0435')),
            ],
        ),
    ]
